spring.application.name=BTG_Pactual_V2

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Habilita override de métodos HTTP (PUT/PATCH/DELETE) usando _method
spring.mvc.hiddenmethod.filter.enabled=true

# JWT
jwt.secret=S3cur3K3yBTGPactual2025!xYz9Km4QwErTyU1OpAsD
jwt.expiration-ms=300000

# Política de bloqueo
jwt.max-failed-attempts=3

# Encriptación AES-256 (clave Base64, 32 bytes = 256 bits)
encriptacion.clave-aes=QlRHUGFjdHVhbDIwMjVBRVNLZXkzMkJ5dGVzWFlaISE=

# DynamoDB
dynamodb.endpoint=http://localhost:8000
dynamodb.region=us-east-1
dynamodb.access-key=fakeMyKeyId
dynamodb.secret-key=fakeSecretAccessKey
