spring.application.name=BTG_Pactual_V2

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Habilita override de métodos HTTP (PUT/PATCH/DELETE) usando _method
spring.mvc.hiddenmethod.filter.enabled=true
